version: "3.2"
services:
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: testing
#    ports:
 #     - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - resolute
  web:
    build: .
    command: npm start app.js
    depends_on:
      - db
    environment:
      DB: 'postgressql://postgres:test123@db:5432/testing'
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - resolute
networks:
  resolute:
    external:
      name: resolute
